pipeline {
    agent {
        label 'home'
    }

    stages {
        stage('Init submodules') {
            steps {
                sh '''
                    git config --global url."https://github.com/".insteadOf "git@github.com:"
                    git submodule sync --recursive
                    git submodule update --init --recursive
                '''
            }
        }

        stage('SSH key configuration') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'id_home_lab', keyFileVariable: 'SSH_KEY'),
                                 sshUserPrivateKey(credentialsId: 'id_home_lab_pub', keyFileVariable: 'SSH_KEY_PUB')]) {
                    sh '''
                        mkdir -p /root/.ssh
                        cp "$SSH_KEY" /root/.ssh/id_home_lab
                        cp "$SSH_KEY_PUB" /root/.ssh/id_home_lab.pub
                        chmod 600 /root/.ssh/id_home_lab
                        chmod 600 /root/.ssh/id_home_lab.pub
                    '''
                }
            }
        }

        stage('Build docker') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'nexus_domain', variable: 'NEXUS_DOMAIN'),
                                     string(credentialsId: 'nexus_user', variable: 'NEXUS_USER'),
                                     string(credentialsId: 'nexus_pass', variable: 'NEXUS_PASS')
                    ]) {

                        sh '''
                            echo "[INFO] Generating Docker config.json for Kaniko"
                            mkdir -p $HOME/.docker
                            echo "{\"auths\":{\"$REGISTRY\":{\"auth\":\"$(echo -n $NEXUS_USER:$NEXUS_PASS | base64)\"}}}" > $HOME/.docker/config.json

                            echo "[INFO] Running Kaniko build..."
                            which kaniko-executor || echo "[ERROR] kaniko-executor not found in PATH!"

                            kaniko-executor \
                              --dockerfile docker/Dockerfile \
                              --context . \
                              --destination ${NEXUS_DOMAIN}/jenkins-agent-lts:latest \
                              --build-arg NODE_VERSION=22.18.0 \
                              --build-arg JAVA_VERSION=21 \
                              --build-arg GRADLE_VERSION=8.10.2 \
                              --build-arg PYTHON_VERSION=3.11
                        '''
                    }
                }
            }
        }
    }
}