pipeline {
    agent {
        docker {
            args  '--privileged -e STORAGE_DRIVER=vfs -e BUILDAH_ISOLATION=chroot'
        }
        label 'home'
    }

    stages {
        stage('Init submodules') {
            steps {
                sh '''
                    git config --global url."https://github.com/".insteadOf "git@github.com:"
                    git submodule sync --recursive
                    git submodule update --init --recursive
                '''
            }
        }

        stage('SSH key configuration') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'id_home_lab', keyFileVariable: 'SSH_KEY'),
                                 sshUserPrivateKey(credentialsId: 'id_home_lab_pub', keyFileVariable: 'SSH_KEY_PUB')]) {
                    sh '''
                        mkdir -p /root/.ssh
                        cp "$SSH_KEY" /root/.ssh/id_home_lab
                        cp "$SSH_KEY_PUB" /root/.ssh/id_home_lab.pub
                        chmod 600 /root/.ssh/id_home_lab
                        chmod 600 /root/.ssh/id_home_lab.pub
                    '''
                }
            }
        }

        stage('Build docker') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'nexus_domain', variable: 'NEXUS_DOMAIN'),
                                     string(credentialsId: 'nexus_user', variable: 'NEXUS_USER'),
                                     string(credentialsId: 'nexus_pass', variable: 'NEXUS_PASS')]) {
                        sh '''
                            echo "[INFO] Login into Nexus registry..."
                              BUILDAH_ISOLATION=chroot STORAGE_DRIVER=vfs \
                                buildah login -u "${NEXUS_USER}" -p "${NEXUS_PASS}" "${NEXUS_DOMAIN}"

                              echo "[INFO] Running Buildah build..."
                              BUILDAH_ISOLATION=chroot STORAGE_DRIVER=vfs \
                                buildah bud \
                                  -f docker/Dockerfile \
                                  -t ${NEXUS_DOMAIN}/myapp:latest \
                                  --build-arg NODE_VERSION=${NODE_VERSION} \
                                  --build-arg JAVA_VERSION=${JAVA_VERSION} \
                                  --build-arg GRADLE_VERSION=${GRADLE_VERSION} \
                                  --build-arg PYTHON_VERSION=${PYTHON_VERSION} \
                                  .

                              echo "[INFO] Pushing image to registry..."
                              BUILDAH_ISOLATION=chroot STORAGE_DRIVER=vfs \
                                buildah push ${NEXUS_DOMAIN}/myapp:latest
                        '''
                    }
                }
            }
        }
    }
}