pipeline {
    agent {
        label 'home'
    }

    stages {
        stage('Init submodules') {
            steps {
                sh '''
                    git config --global url."https://github.com/".insteadOf "git@github.com:"
                    git submodule sync --recursive
                    git submodule update --init --recursive
                '''
            }
        }

        stage('SSH key configuration') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'id_home_lab', keyFileVariable: 'SSH_KEY'),
                                 sshUserPrivateKey(credentialsId: 'id_home_lab_pub', keyFileVariable: 'SSH_KEY_PUB')]) {
                    sh '''
                        mkdir -p /root/.ssh
                        cp "$SSH_KEY" /root/.ssh/id_home_lab
                        cp "$SSH_KEY_PUB" /root/.ssh/id_home_lab.pub
                        chmod 600 /root/.ssh/id_home_lab
                        chmod 600 /root/.ssh/id_home_lab.pub
                    '''
                }
            }
        }

        stage('Build docker') {
            steps {
                script {
                    sh '''
                        buildctl build \
                          --frontend dockerfile.v0 \
                          --local context=. \
                          --local dockerfile=docker \
                          --opt filename=Dockerfile \
                          --opt build-arg:NODE_VERSION=22.18.0 \
                          --opt build-arg:JAVA_VERSION=21 \
                          --opt build-arg:GRADLE_VERSION=8.10.2 \
                          --opt build-arg:PYTHON_VERSION=3.11 \
                          --output type=docker,name=jenkins-agent-lts:latest | docker load
                    '''
                }
            }
        }
    }
}